services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    # image: docsdev
    # build:
    #   context: .
    #   dockerfile: ./dev/Dockerfile
    volumes:
      - .:/docs
    ports:
      - "8000:8000"    
