name: cicd
on:
  push:
    branches:
      - master

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: dump vars
        run: |
          echo ${{ vars.IS_GITEA }}
          echo ${{ vars.DOCKER_REGISTRY }}
          echo ${{ gitea.actor }}
          echo ${{ gitea.sha }}
  
      - name: Check IS_GITEA variable
        run: |
          if [ "${{ vars.GITEA_ENV }}" != "true" ]; then
            echo "This is not Gitea. Skipping action."
            exit 0
          fi
          echo "Running on Gitea. Proceeding with action."

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Gitea Package registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.USER_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ gitea.actor }}/docs:latest, ${{ gitea.actor }}/docs:${{ gitea.sha }}
