name: cicd
on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    if: ${{ vars.IS_GITEA }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{  gitea.sha }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Gitea Package registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.ACTIONS_PAT }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ gitea.actor }}/docs:latest
            ${{ vars.DOCKER_REGISTRY }}/${{ gitea.actor }}/docs:${{ gitea.sha }}
    
  update-devops-repo:
    if: ${{ vars.IS_GITEA }}
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{  gitea.sha }}

      - name: Checkout homelab repo
        uses: actions/checkout@v4
        with: 
          repository: ${{ gitea.actor }}/homelab
          ref: master

      - name: Replace SHA in deployment.yaml
        run: |
          FILE="kubernetes/applications/docs/deployment.yaml"
          sed "s#${{ secrets.GITEA_URL }}/${{ gitea.actor }}/docs:[^:]*#${{ secrets.GITEA_URL }}/${{ gitea.actor }}/docs:${{ gitea.sha }}#" "$FILE"
          cat "$FILE"

      - name: Status
        run: |
          git status
      - name: Commit and push changes
        run: |
          git config --global user.name "Gitea Actions Bot"
          git config --global user.email "actions@${{ vars.DOCKER_REGISTRY }}"
          git add kubernetes/applications/docs/deployment.yaml
          git commit -m "Update image SHA to ${{ github.sha }}"
          git push https://${{ gitea.actor }}:${{ secrets.ACTIONS_PAT }}@${{ vars.DOCKER_REGISTRY }}/${{ gitea.actor }}/homelab.git main
