name: gh-pages
on:
  push:
    branches:
      - master
 
permissions:
  contents: write
jobs:
  deploy:
    if: ${{ ! vars.IS_GITEA }}
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \
              mkdocs-material \
              mkdocs-minify-plugin \
              mkdocs-redirects \
              mkdocs-rss-plugin
      - name: Build and push
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          REPO_URL: ${{ vars.REPO_URL }}
        run: mkdocs gh-deploy --force
