name: gh-pages
on:
  push:
    branches:
      - master 
permissions:
  contents: write
jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check IS_GITEA variable
        run: |
          if [ ${{ vars.GITEA_ENV }} != "true" ]; then
            echo "This is not Gitea. Skipping action."
            exit 0
          fi
          echo "Running on Gitea. Proceeding with action."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
